#------------------------------------------------------------------------------#
# This makefile was (originally) generated by 'cbp2make' tool rev.147          #
# And reworked by Stephen Morgan with tweaks by Ian V.                         #
#------------------------------------------------------------------------------#

WORKDIR = `pwd`

CC = gcc
CXX = g++
AR = ar
LD = g++
BISON = /bin/bison
FLEX = /bin/flex

INC = -Isrc -Iinclude -I/usr/local/include
CFLAGS = -Wall -std=c++14 -fPIC -O3
LIBDIR =
LIB =
LDFLAGS = -lrt
SRCDIR = src
OBJDIR = .objs
OUTDIR = bin
DEPFLAGS_CC = -MMD -MP -MF $(@:.o=.cc.d)
DEPFLAGS_CXX = -MMD -MP -MF $(@:.o=.cpp.d)

main: \
	ivymaster \
	ivydriver \
	remove_empty_columns

#
# base definitions section
#

parser/lexyacc/ivy.scanner.cc: parser/lexyacc/ivy.l
	$(FLEX) -o parser/lexyacc/ivy.scanner.cc parser/lexyacc/ivy.l

parser/lexyacc/ivy.parser.cc: parser/lexyacc/ivy.y
	$(BISON) -t -v -d parser/lexyacc/ivy.y -o parser/lexyacc/ivy.parser.cc

$(SRCDIR)/hosts/hosts.scanner.cc: $(SRCDIR)/hosts/hosts.l
	$(FLEX) -o $(SRCDIR)/hosts/hosts.scanner.cc $(SRCDIR)/hosts/hosts.l

$(SRCDIR)/hosts/hosts.parser.cc: $(SRCDIR)/hosts/hosts.y
	$(BISON) -t -v -d $(SRCDIR)/hosts/hosts.y -o $(SRCDIR)/hosts/hosts.parser.cc

$(SRCDIR)/select/select.scanner.cc: $(SRCDIR)/select/select.l
	$(FLEX) -o $(SRCDIR)/select/select.scanner.cc $(SRCDIR)/select/select.l

$(SRCDIR)/select/select.parser.cc: $(SRCDIR)/select/select.y
	$(BISON) -t -v -d $(SRCDIR)/select/select.y -o $(SRCDIR)/select/select.parser.cc

#
# ivymaster definitions section
#

INC_IVYMASTER = $(INC) -Iparser/include -Iparser/lexyacc -Iivy/include
CFLAGS_IVYMASTER = $(CFLAGS) -pthread
LIBDIR_IVYMASTER = $(LIBDIR) -L/usr/lib64
LIB_IVYMASTER = $(LIB)
LDFLAGS_IVYMASTER = $(LDFLAGS) -lrt -lpthread -lssl -lcrypto -lboost_system -lcpprest
OBJDIR_IVYMASTER = $(OBJDIR)/.ivymaster
OUTFILE_IVYMASTER = $(OUTDIR)/ivy
CXX_IVYMASTER = $(CXX) $(DEPFLAGS_CXX) $(INC_IVYMASTER) $(CFLAGS_IVYMASTER) -o $@ -c
CC_IVYMASTER  = $(CC) $(DEPFLAGS_CC) $(INC_IVYMASTER) $(CFLAGS_IVYMASTER) -o $@ -c

$(OBJDIR_IVYMASTER)/__/LUN_discovery/src/%.o : ../LUN_discovery/src/%.cpp $(OBJDIR_IVYMASTER)/__/LUN_discovery/src/%.cpp.d
	$(CXX_IVYMASTER) $<

$(OBJDIR_IVYMASTER)/parser/lexyacc/%.o : parser/lexyacc/%.cc $(OBJDIR_IVYMASTER)/parser/lexyacc/%.cc.d
	$(CC_IVYMASTER) $<

$(OBJDIR_IVYMASTER)/parser/src/%.o : parser/src/%.cpp $(OBJDIR_IVYMASTER)/parser/src/%.cpp.d
	$(CXX_IVYMASTER) $<

$(OBJDIR_IVYMASTER)/src/hosts/%.o : $(SRCDIR)/hosts/%.cc $(OBJDIR_IVYMASTER)/src/hosts/%.cc.d
	$(CC_IVYMASTER) $<

$(OBJDIR_IVYMASTER)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_IVYMASTER)/src/%.cpp.d
	$(CXX_IVYMASTER) $<

$(OBJDIR_IVYMASTER)/src/select/select.parser.o: $(SRCDIR)/select/select.parser.cc
	$(CC_IVYMASTER) $<

$(OBJDIR_IVYMASTER)/src/select/select.scanner.o: $(SRCDIR)/select/select.scanner.cc
	$(CC_IVYMASTER) $<

$(OBJDIR_IVYMASTER)/src/JSON_select.o: $(SRCDIR)/JSON_select.cpp 
	$(CXX_IVYMASTER) $<

OBJFILES_IVYMASTER = \
	$(OBJDIR_IVYMASTER)/__/LUN_discovery/src/printableAndHex.o \
	$(OBJDIR_IVYMASTER)/parser/lexyacc/ivy.parser.o \
	$(OBJDIR_IVYMASTER)/parser/lexyacc/ivy.scanner.o \
	$(OBJDIR_IVYMASTER)/parser/src/Arg.o \
	$(OBJDIR_IVYMASTER)/parser/src/Block.o \
	$(OBJDIR_IVYMASTER)/parser/src/Builtin.o \
	$(OBJDIR_IVYMASTER)/parser/src/Frame.o \
	$(OBJDIR_IVYMASTER)/parser/src/Ivy_pgm.o \
	$(OBJDIR_IVYMASTER)/parser/src/IvyscriptLine.o \
	$(OBJDIR_IVYMASTER)/parser/src/main.o \
	$(OBJDIR_IVYMASTER)/parser/src/OverloadSet.o \
	$(OBJDIR_IVYMASTER)/parser/src/Stmt_nested_Block.o \
	$(OBJDIR_IVYMASTER)/parser/src/Stmt.o \
	$(OBJDIR_IVYMASTER)/parser/src/SymbolTableEntry.o \
	$(OBJDIR_IVYMASTER)/parser/src/Type.o \
	$(OBJDIR_IVYMASTER)/parser/src/Xpr.o \
	$(OBJDIR_IVYMASTER)/src/Accumulators_by_io_type.o \
	$(OBJDIR_IVYMASTER)/src/AttributeNameCombo.o \
	$(OBJDIR_IVYMASTER)/src/csvfile.o \
	$(OBJDIR_IVYMASTER)/src/dedupe_method.o \
	$(OBJDIR_IVYMASTER)/src/discover_luns.o \
	$(OBJDIR_IVYMASTER)/src/GatherData.o \
	$(OBJDIR_IVYMASTER)/src/hosts/hosts.parser.o \
	$(OBJDIR_IVYMASTER)/src/hosts/hosts.scanner.o \
	$(OBJDIR_IVYMASTER)/src/hosts_list.o \
	$(OBJDIR_IVYMASTER)/src/IosequencerInput.o \
	$(OBJDIR_IVYMASTER)/src/IosequencerInputRollup.o \
	$(OBJDIR_IVYMASTER)/src/ivy_engine_create_delete_rollup.o \
	$(OBJDIR_IVYMASTER)/src/ivy_engine_create_delete_workload.o \
	$(OBJDIR_IVYMASTER)/src/ivy_engine_edit_rollup.o \
	$(OBJDIR_IVYMASTER)/src/ivy_engine_get_set.o \
	$(OBJDIR_IVYMASTER)/src/ivy_engine_go.o \
	$(OBJDIR_IVYMASTER)/src/ivy_engine.o \
	$(OBJDIR_IVYMASTER)/src/ivy_engine_startup.o \
	$(OBJDIR_IVYMASTER)/src/ivyhelpers.o \
	$(OBJDIR_IVYMASTER)/src/ivylinuxcpubusy.o \
	$(OBJDIR_IVYMASTER)/src/ivymaster_signal_handler.o \
	$(OBJDIR_IVYMASTER)/src/ivytime.o \
	$(OBJDIR_IVYMASTER)/src/JSON_select.o \
	$(OBJDIR_IVYMASTER)/src/LDEVset.o \
	$(OBJDIR_IVYMASTER)/src/ListOfNameEqualsValueList.o \
	$(OBJDIR_IVYMASTER)/src/ListOfWorkloadIDs.o \
	$(OBJDIR_IVYMASTER)/src/logger.o \
	$(OBJDIR_IVYMASTER)/src/LUN.o \
	$(OBJDIR_IVYMASTER)/src/LUNpointerList.o \
	$(OBJDIR_IVYMASTER)/src/MeasureController.o \
	$(OBJDIR_IVYMASTER)/src/MeasureCtlr.o \
	$(OBJDIR_IVYMASTER)/src/measurement.o \
	$(OBJDIR_IVYMASTER)/src/multi_measure.o \
	$(OBJDIR_IVYMASTER)/src/NameEqualsValueList.o \
	$(OBJDIR_IVYMASTER)/src/nestedit.o \
	$(OBJDIR_IVYMASTER)/src/ParameterValueLookupTable.o \
	$(OBJDIR_IVYMASTER)/src/pattern.o \
	$(OBJDIR_IVYMASTER)/src/pipe_driver_gather.o \
	$(OBJDIR_IVYMASTER)/src/pipe_driver_subthread.o \
	$(OBJDIR_IVYMASTER)/src/prepare_dedupe.o \
	$(OBJDIR_IVYMASTER)/src/process_cmddev_commands.o \
	$(OBJDIR_IVYMASTER)/src/RestBaseUri.o \
	$(OBJDIR_IVYMASTER)/src/RestCsvqueryUri.o \
	$(OBJDIR_IVYMASTER)/src/RestEngineUri.o \
	$(OBJDIR_IVYMASTER)/src/RestHandler.o \
	$(OBJDIR_IVYMASTER)/src/RestLogsUri.o \
	$(OBJDIR_IVYMASTER)/src/RestRollupsUri.o \
	$(OBJDIR_IVYMASTER)/src/RestSessionsUri.o \
	$(OBJDIR_IVYMASTER)/src/RestWorkloadsUri.o \
	$(OBJDIR_IVYMASTER)/src/rollup_Hitachi_RAID_data.o \
	$(OBJDIR_IVYMASTER)/src/RollupInstance.o \
	$(OBJDIR_IVYMASTER)/src/RollupSet.o \
	$(OBJDIR_IVYMASTER)/src/RollupType.o \
	$(OBJDIR_IVYMASTER)/src/RunningStat.o \
	$(OBJDIR_IVYMASTER)/src/run_subinterval_sequence.o \
	$(OBJDIR_IVYMASTER)/src/select/select.parser.o \
	$(OBJDIR_IVYMASTER)/src/select/select.scanner.o \
	$(OBJDIR_IVYMASTER)/src/skew_weight.o \
	$(OBJDIR_IVYMASTER)/src/studentsTdistribution.o \
	$(OBJDIR_IVYMASTER)/src/Subinterval_CPU.o \
	$(OBJDIR_IVYMASTER)/src/Subinterval_detail_line.o \
	$(OBJDIR_IVYMASTER)/src/SubintervalOutput.o \
	$(OBJDIR_IVYMASTER)/src/SubintervalRollup.o \
	$(OBJDIR_IVYMASTER)/src/Subsystem.o \
	$(OBJDIR_IVYMASTER)/src/subsystem_summary_data.o \
	$(OBJDIR_IVYMASTER)/src/Test_config_thumbnail.o \
	$(OBJDIR_IVYMASTER)/src/WorkloadID.o \
	$(OBJDIR_IVYMASTER)/src/WorkloadTracker.o \
	$(OBJDIR_IVYMASTER)/src/WorkloadTrackerPointerList.o

DEPFILES_CXX_IVYMASTER := $(OBJFILES_IVYMASTER:%.o=%.cpp.d)
$(DEPFILES_CXX_IVYMASTER):
include $(wildcard $(DEPFILES_CXX_IVYMASTER))

DEPFILES_CC_IVYMASTER := $(OBJFILES_IVYMASTER:%.o=%.cc.d)
$(DEPFILES_CC_IVYMASTER):
include $(wildcard $(DEPFILES_CC_IVYMASTER))

#
# ivydriver definitions section
#

INC_IVYDRIVER = $(INC) -Iparser/include -Iparser/lexyacc -Iivy/include -I../LUN_discovery/include -I/usr/include
CFLAGS_IVYDRIVER = $(CFLAGS) -pthread
LIBDIR_IVYDRIVER = $(LIBDIR)
LIB_IVYDRIVER = $(LIB)
LDFLAGS_IVYDRIVER = $(LDFLAGS) -lrt -lpthread -lssl -luring
OBJDIR_IVYDRIVER = $(OBJDIR)/.ivydriver
OUTFILE_IVYDRIVER = $(OUTDIR)/ivydriver
CXX_IVYDRIVER = $(CXX) $(DEPFLAGS_CXX) $(INC_IVYDRIVER) $(CFLAGS_IVYDRIVER) -o $@ -c
CC_IVYDRIVER  = $(CC) $(DEPFLAGS_CC) $(INC_IVYDRIVER) $(CFLAGS_IVYDRIVER) -o $@ -c

$(OBJDIR_IVYDRIVER)/__/LUN_discovery/src/%.o : ../LUN_discovery/src/%.cpp $(OBJDIR_IVYDRIVER)/__/LUN_discovery/src/%.cpp.d
	$(CXX_IVYDRIVER) $<

$(OBJDIR_IVYDRIVER)/parser/lexyacc/%.o : parser/lexyacc/%.cc $(OBJDIR_IVYDRIVER)/parser/lexyacc/%.cc.d
	$(CC_IVYDRIVER) $<

$(OBJDIR_IVYDRIVER)/parser/src/%.o : parser/src/%.cpp $(OBJDIR_IVYDRIVER)/parser/src/%.cpp.d
	$(CXX_IVYDRIVER) $<

$(OBJDIR_IVYDRIVER)/src/hosts/%.o : $(SRCDIR)/hosts/%.cc $(OBJDIR_IVYDRIVER)/src/hosts/%.cc.d
	$(CC_IVYDRIVER) $<

$(OBJDIR_IVYDRIVER)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_IVYDRIVER)/src/%.cpp.d
	$(CXX_IVYDRIVER) $<

$(OBJDIR_IVYDRIVER)/src/select/select.parser.o: $(SRCDIR)/select/select.parser.cc
	$(CC_IVYDRIVER) $<

$(OBJDIR_IVYDRIVER)/src/select/select.scanner.o: $(SRCDIR)/select/select.scanner.cc
	$(CC_IVYDRIVER) $<

$(OBJDIR_IVYDRIVER)/src/JSON_select.o: $(SRCDIR)/JSON_select.cpp 
	$(CXX_IVYDRIVER) $<

OBJFILES_IVYDRIVER = \
	$(OBJDIR_IVYDRIVER)/__/LUN_discovery/src/printableAndHex.o \
	$(OBJDIR_IVYDRIVER)/src/Accumulators_by_io_type.o \
	$(OBJDIR_IVYDRIVER)/src/AttributeNameCombo.o \
	$(OBJDIR_IVYDRIVER)/src/Count_by_workloadID.o \
	$(OBJDIR_IVYDRIVER)/src/DedupeConstantRatioRegulator.o \
	$(OBJDIR_IVYDRIVER)/src/dedupe_method.o \
	$(OBJDIR_IVYDRIVER)/src/DedupeRoundRobinRegulator.o \
	$(OBJDIR_IVYDRIVER)/src/DedupeRoundRobinSingleton.o \
	$(OBJDIR_IVYDRIVER)/src/DedupeTargetSpreadRegulator.o \
	$(OBJDIR_IVYDRIVER)/src/discover_luns.o \
	$(OBJDIR_IVYDRIVER)/src/Eyeo.o \
	$(OBJDIR_IVYDRIVER)/src/IosequencerInput.o \
	$(OBJDIR_IVYDRIVER)/src/IosequencerInputRollup.o \
	$(OBJDIR_IVYDRIVER)/src/Iosequencer.o \
	$(OBJDIR_IVYDRIVER)/src/IosequencerRandomIndependent.o \
	$(OBJDIR_IVYDRIVER)/src/IosequencerRandom.o \
	$(OBJDIR_IVYDRIVER)/src/IosequencerRandomSteady.o \
	$(OBJDIR_IVYDRIVER)/src/IosequencerSequential.o \
	$(OBJDIR_IVYDRIVER)/src/ivydriver.o \
	$(OBJDIR_IVYDRIVER)/src/ivyhelpers.o \
	$(OBJDIR_IVYDRIVER)/src/ivylinuxcpubusy.o \
	$(OBJDIR_IVYDRIVER)/src/ivytime.o \
	$(OBJDIR_IVYDRIVER)/src/LDEVset.o \
	$(OBJDIR_IVYDRIVER)/src/ListOfWorkloadIDs.o \
	$(OBJDIR_IVYDRIVER)/src/logger.o \
	$(OBJDIR_IVYDRIVER)/src/LUN.o \
	$(OBJDIR_IVYDRIVER)/src/pattern.o \
	$(OBJDIR_IVYDRIVER)/src/pipe_line_reader.o \
	$(OBJDIR_IVYDRIVER)/src/RunningStat.o \
	$(OBJDIR_IVYDRIVER)/src/studentsTdistribution.o \
	$(OBJDIR_IVYDRIVER)/src/Subinterval.o \
	$(OBJDIR_IVYDRIVER)/src/SubintervalOutput.o \
	$(OBJDIR_IVYDRIVER)/src/TestLUN.o \
	$(OBJDIR_IVYDRIVER)/src/unique_words.o \
	$(OBJDIR_IVYDRIVER)/src/WorkloadID.o \
	$(OBJDIR_IVYDRIVER)/src/Workload.o \
	$(OBJDIR_IVYDRIVER)/src/WorkloadThread.o \
	$(OBJDIR_IVYDRIVER)/src/WorkloadTracker.o \
	$(OBJDIR_IVYDRIVER)/src/WorkloadTrackerPointerList.o

DEPFILES_CXX_IVYDRIVER := $(OBJFILES_IVYDRIVER:%.o=%.cpp.d)
$(DEPFILES_CXX_IVYDRIVER):
include $(wildcard $(DEPFILES_CXX_IVYDRIVER))

DEPFILES_CC_IVYDRIVER := $(OBJFILES_IVYDRIVER:%.o=%.cc.d)
$(DEPFILES_CC_IVYDRIVER):
include $(wildcard $(DEPFILES_CC_IVYDRIVER))

#
# clear_hung_ivy_threads definitions section
#

INC_CLEAR_HUNG_IVY_THREADS = $(INC)
CFLAGS_CLEAR_HUNG_IVY_THREADS = $(CFLAGS)
LIBDIR_CLEAR_HUNG_IVY_THREADS = $(LIBDIR)
LIB_CLEAR_HUNG_IVY_THREADS = $(LIB)
LDFLAGS_CLEAR_HUNG_IVY_THREADS = $(LDFLAGS)
OBJDIR_CLEAR_HUNG_IVY_THREADS = $(OBJDIR)/.clear_hung_ivy_threads
OUTFILE_CLEAR_HUNG_IVY_THREADS = $(OUTDIR)/clear_hung_ivy_threads
CXX_CLEAR_HUNG_IVY_THREADS = $(CXX) $(DEPFLAGS_CXX) $(INC_CLEAR_HUNG_IVY_THREADS) $(CFLAGS_CLEAR_HUNG_IVY_THREADS) -o $@ -c

$(OBJDIR_CLEAR_HUNG_IVY_THREADS)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CLEAR_HUNG_IVY_THREADS)/src/%.cpp.d
	$(CXX_CLEAR_HUNG_IVY_THREADS) $<

OBJFILES_CLEAR_HUNG_IVY_THREADS = \
	$(OBJDIR_CLEAR_HUNG_IVY_THREADS)/src/clear_hung_ivy_threads.o \
	$(OBJDIR_CLEAR_HUNG_IVY_THREADS)/src/ivyhelpers.o \
	$(OBJDIR_CLEAR_HUNG_IVY_THREADS)/src/ivytime.o

DEPFILES_CXX_CLEAR_HUNG_IVY_THREADS := $(OBJFILES_CLEAR_HUNG_IVY_THREADS:%.o=%.cpp.d)
$(DEPFILES_CXX_CLEAR_HUNG_IVY_THREADS):
include $(wildcard $(DEPFILES_CXX_CLEAR_HUNG_IVY_THREADS))

#
# makedict definitions section
#

INC_MAKEDICT = $(INC)
CFLAGS_MAKEDICT = $(CFLAGS)
LIBDIR_MAKEDICT = $(LIBDIR)
LIB_MAKEDICT = $(LIB)
LDFLAGS_MAKEDICT = $(LDFLAGS)
OBJDIR_MAKEDICT = $(OBJDIR)/.makedict
OUTFILE_MAKEDICT = $(OUTDIR)/makedict
CXX_MAKEDICT = $(CXX) $(DEPFLAGS_CXX) $(INC_MAKEDICT) $(CFLAGS_MAKEDICT) -o $@ -c

$(OBJDIR_MAKEDICT)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_MAKEDICT)/src/%.cpp.d
	$(CXX_MAKEDICT) $<

OBJFILES_MAKEDICT = \
	$(OBJDIR_MAKEDICT)/src/makedict.o

DEPFILES_CXX_MAKEDICT := $(OBJFILES_MAKEDICT:%.o=%.cpp.d)
$(DEPFILES_CXX_MAKEDICT):
include $(wildcard $(DEPFILES_CXX_MAKEDICT))

#
# csv_rows definitions section
#

INC_CSV_ROWS = $(INC)
CFLAGS_CSV_ROWS = $(CFLAGS)
LIBDIR_CSV_ROWS = $(LIBDIR)
LIB_CSV_ROWS = $(LIB)
LDFLAGS_CSV_ROWS = $(LDFLAGS)
OBJDIR_CSV_ROWS = $(OBJDIR)/.csv_rows
OUTFILE_CSV_ROWS = $(OUTDIR)/csv_rows
CXX_CSV_ROWS = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_ROWS) $(CFLAGS_CSV_ROWS) -o $@ -c

$(OBJDIR_CSV_ROWS)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_ROWS)/src/%.cpp.d
	$(CXX_CSV_ROWS) $<

OBJFILES_CSV_ROWS = \
	$(OBJDIR_CSV_ROWS)/src/csv_rows.o \
	$(OBJDIR_CSV_ROWS)/src/csv_usage.o \
	$(OBJDIR_CSV_ROWS)/src/csvfile.o \
	$(OBJDIR_CSV_ROWS)/src/ivyhelpers.o \
	$(OBJDIR_CSV_ROWS)/src/ivytime.o

DEPFILES_CXX_CSV_ROWS := $(OBJFILES_CSV_ROWS:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_ROWS):
include $(wildcard $(DEPFILES_CXX_CSV_ROWS))

#
# csv_header_columns definitions section
#

INC_CSV_HEADER_COLUMNS = $(INC)
CFLAGS_CSV_HEADER_COLUMNS = $(CFLAGS)
LIBDIR_CSV_HEADER_COLUMNS = $(LIBDIR)
LIB_CSV_HEADER_COLUMNS = $(LIB)
LDFLAGS_CSV_HEADER_COLUMNS = $(LDFLAGS)
OBJDIR_CSV_HEADER_COLUMNS = $(OBJDIR)/.csv_header_columns
OUTFILE_CSV_HEADER_COLUMNS = $(OUTDIR)/csv_header_columns
CXX_CSV_HEADER_COLUMNS = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_HEADER_COLUMNS) $(CFLAGS_CSV_HEADER_COLUMNS) -o $@ -c

$(OBJDIR_CSV_HEADER_COLUMNS)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_HEADER_COLUMNS)/src/%.cpp.d
	$(CXX_CSV_HEADER_COLUMNS) $<

OBJFILES_CSV_HEADER_COLUMNS = \
	$(OBJDIR_CSV_HEADER_COLUMNS)/src/csv_header_columns.o \
	$(OBJDIR_CSV_HEADER_COLUMNS)/src/csv_usage.o \
	$(OBJDIR_CSV_HEADER_COLUMNS)/src/csvfile.o \
	$(OBJDIR_CSV_HEADER_COLUMNS)/src/ivyhelpers.o \
	$(OBJDIR_CSV_HEADER_COLUMNS)/src/ivytime.o

DEPFILES_CXX_CSV_HEADER_COLUMNS := $(OBJFILES_CSV_HEADER_COLUMNS:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_HEADER_COLUMNS):
include $(wildcard $(DEPFILES_CXX_CSV_HEADER_COLUMNS))

#
# csv_columns_in_row definitions section
#

INC_CSV_COLUMNS_IN_ROW = $(INC)
CFLAGS_CSV_COLUMNS_IN_ROW = $(CFLAGS)
LIBDIR_CSV_COLUMNS_IN_ROW = $(LIBDIR)
LIB_CSV_COLUMNS_IN_ROW = $(LIB)
LDFLAGS_CSV_COLUMNS_IN_ROW = $(LDFLAGS)
OBJDIR_CSV_COLUMNS_IN_ROW = $(OBJDIR)/.csv_columns_in_row
OUTFILE_CSV_COLUMNS_IN_ROW = $(OUTDIR)/csv_columns_in_row
CXX_CSV_COLUMNS_IN_ROW = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_COLUMNS_IN_ROW) $(CFLAGS_CSV_COLUMNS_IN_ROW) -o $@ -c

$(OBJDIR_CSV_COLUMNS_IN_ROW)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_COLUMNS_IN_ROW)/src/%.cpp.d
	$(CXX_CSV_COLUMNS_IN_ROW) $<

OBJFILES_CSV_COLUMNS_IN_ROW = \
	$(OBJDIR_CSV_COLUMNS_IN_ROW)/src/csv_columns_in_row.o \
	$(OBJDIR_CSV_COLUMNS_IN_ROW)/src/csv_usage.o \
	$(OBJDIR_CSV_COLUMNS_IN_ROW)/src/csvfile.o \
	$(OBJDIR_CSV_COLUMNS_IN_ROW)/src/ivyhelpers.o \
	$(OBJDIR_CSV_COLUMNS_IN_ROW)/src/ivytime.o

DEPFILES_CXX_CSV_COLUMNS_IN_ROW := $(OBJFILES_CSV_COLUMNS_IN_ROW:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_COLUMNS_IN_ROW):
include $(wildcard $(DEPFILES_CXX_CSV_COLUMNS_IN_ROW))

#
# csv_column_header definitions section
#

INC_CSV_COLUMN_HEADER = $(INC)
CFLAGS_CSV_COLUMN_HEADER = $(CFLAGS)
LIBDIR_CSV_COLUMN_HEADER = $(LIBDIR)
LIB_CSV_COLUMN_HEADER = $(LIB)
LDFLAGS_CSV_COLUMN_HEADER = $(LDFLAGS)
OBJDIR_CSV_COLUMN_HEADER = $(OBJDIR)/.csv_column_header
OUTFILE_CSV_COLUMN_HEADER = $(OUTDIR)/csv_column_header
CXX_CSV_COLUMN_HEADER = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_COLUMN_HEADER) $(CFLAGS_CSV_COLUMN_HEADER) -o $@ -c

$(OBJDIR_CSV_COLUMN_HEADER)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_COLUMN_HEADER)/src/%.cpp.d
	$(CXX_CSV_COLUMN_HEADER) $<

OBJFILES_CSV_COLUMN_HEADER = \
	$(OBJDIR_CSV_COLUMN_HEADER)/src/csv_column_header.o \
	$(OBJDIR_CSV_COLUMN_HEADER)/src/csv_usage.o \
	$(OBJDIR_CSV_COLUMN_HEADER)/src/csvfile.o \
	$(OBJDIR_CSV_COLUMN_HEADER)/src/ivyhelpers.o \
	$(OBJDIR_CSV_COLUMN_HEADER)/src/ivytime.o

DEPFILES_CXX_CSV_COLUMN_HEADER := $(OBJFILES_CSV_COLUMN_HEADER:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_COLUMN_HEADER):
include $(wildcard $(DEPFILES_CXX_CSV_COLUMN_HEADER))

#
# csv_raw_cell_value definitions section
#

INC_CSV_RAW_CELL_VALUE = $(INC)
CFLAGS_CSV_RAW_CELL_VALUE = $(CFLAGS)
LIBDIR_CSV_RAW_CELL_VALUE = $(LIBDIR)
LIB_CSV_RAW_CELL_VALUE = $(LIB)
LDFLAGS_CSV_RAW_CELL_VALUE = $(LDFLAGS)
OBJDIR_CSV_RAW_CELL_VALUE = $(OBJDIR)/.csv_raw_cell_value
OUTFILE_CSV_RAW_CELL_VALUE = $(OUTDIR)/csv_raw_cell_value
CXX_CSV_RAW_CELL_VALUE = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_RAW_CELL_VALUE) $(CFLAGS_CSV_RAW_CELL_VALUE) -o $@ -c

$(OBJDIR_CSV_RAW_CELL_VALUE)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_RAW_CELL_VALUE)/src/%.cpp.d
	$(CXX_CSV_RAW_CELL_VALUE) $<

OBJFILES_CSV_RAW_CELL_VALUE = \
	$(OBJDIR_CSV_RAW_CELL_VALUE)/src/csv_raw_cell_value.o \
	$(OBJDIR_CSV_RAW_CELL_VALUE)/src/csv_usage.o \
	$(OBJDIR_CSV_RAW_CELL_VALUE)/src/csvfile.o \
	$(OBJDIR_CSV_RAW_CELL_VALUE)/src/ivyhelpers.o \
	$(OBJDIR_CSV_RAW_CELL_VALUE)/src/ivytime.o

DEPFILES_CXX_CSV_RAW_CELL_VALUE := $(OBJFILES_CSV_RAW_CELL_VALUE:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_RAW_CELL_VALUE):
include $(wildcard $(DEPFILES_CXX_CSV_RAW_CELL_VALUE))

#
# csv_cell_value definitions section
#

INC_CSV_CELL_VALUE = $(INC)
CFLAGS_CSV_CELL_VALUE = $(CFLAGS)
LIBDIR_CSV_CELL_VALUE = $(LIBDIR)
LIB_CSV_CELL_VALUE = $(LIB)
LDFLAGS_CSV_CELL_VALUE = $(LDFLAGS)
OBJDIR_CSV_CELL_VALUE = $(OBJDIR)/.csv_cell_value
OUTFILE_CSV_CELL_VALUE = $(OUTDIR)/csv_cell_value
CXX_CSV_CELL_VALUE = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_CELL_VALUE) $(CFLAGS_CSV_CELL_VALUE) -o $@ -c

$(OBJDIR_CSV_CELL_VALUE)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_CELL_VALUE)/src/%.cpp.d
	$(CXX_CSV_CELL_VALUE) $<

OBJFILES_CSV_CELL_VALUE = \
	$(OBJDIR_CSV_CELL_VALUE)/src/csv_cell_value.o \
	$(OBJDIR_CSV_CELL_VALUE)/src/csv_usage.o \
	$(OBJDIR_CSV_CELL_VALUE)/src/csvfile.o \
	$(OBJDIR_CSV_CELL_VALUE)/src/ivyhelpers.o \
	$(OBJDIR_CSV_CELL_VALUE)/src/ivytime.o

DEPFILES_CXX_CSV_CELL_VALUE := $(OBJFILES_CSV_CELL_VALUE:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_CELL_VALUE):
include $(wildcard $(DEPFILES_CXX_CSV_CELL_VALUE))

#
# csv_lookup_column definitions section
#

INC_CSV_LOOKUP_COLUMN = $(INC)
CFLAGS_CSV_LOOKUP_COLUMN = $(CFLAGS)
LIBDIR_CSV_LOOKUP_COLUMN = $(LIBDIR)
LIB_CSV_LOOKUP_COLUMN = $(LIB)
LDFLAGS_CSV_LOOKUP_COLUMN = $(LDFLAGS)
OBJDIR_CSV_LOOKUP_COLUMN = $(OBJDIR)/.csv_lookup_column
OUTFILE_CSV_LOOKUP_COLUMN = $(OUTDIR)/csv_lookup_column
CXX_CSV_LOOKUP_COLUMN = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_LOOKUP_COLUMN) $(CFLAGS_CSV_LOOKUP_COLUMN) -o $@ -c

$(OBJDIR_CSV_LOOKUP_COLUMN)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_LOOKUP_COLUMN)/src/%.cpp.d
	$(CXX_CSV_LOOKUP_COLUMN) $<

OBJFILES_CSV_LOOKUP_COLUMN = \
	$(OBJDIR_CSV_LOOKUP_COLUMN)/src/csv_lookup_column.o \
	$(OBJDIR_CSV_LOOKUP_COLUMN)/src/csv_usage.o \
	$(OBJDIR_CSV_LOOKUP_COLUMN)/src/csvfile.o \
	$(OBJDIR_CSV_LOOKUP_COLUMN)/src/ivyhelpers.o \
	$(OBJDIR_CSV_LOOKUP_COLUMN)/src/ivytime.o

DEPFILES_CXX_CSV_LOOKUP_COLUMN := $(OBJFILES_CSV_LOOKUP_COLUMN:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_LOOKUP_COLUMN):
include $(wildcard $(DEPFILES_CXX_CSV_LOOKUP_COLUMN))

#
# csv_row definitions section
#

INC_CSV_ROW = $(INC)
CFLAGS_CSV_ROW = $(CFLAGS)
LIBDIR_CSV_ROW = $(LIBDIR)
LIB_CSV_ROW = $(LIB)
LDFLAGS_CSV_ROW = $(LDFLAGS)
OBJDIR_CSV_ROW = $(OBJDIR)/.csv_row
OUTFILE_CSV_ROW = $(OUTDIR)/csv_row
CXX_CSV_ROW = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_ROW) $(CFLAGS_CSV_ROW) -o $@ -c

$(OBJDIR_CSV_ROW)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_ROW)/src/%.cpp.d
	$(CXX_CSV_ROW) $<

OBJFILES_CSV_ROW = \
	$(OBJDIR_CSV_ROW)/src/csv_row.o \
	$(OBJDIR_CSV_ROW)/src/csv_usage.o \
	$(OBJDIR_CSV_ROW)/src/csvfile.o \
	$(OBJDIR_CSV_ROW)/src/ivyhelpers.o \
	$(OBJDIR_CSV_ROW)/src/ivytime.o

DEPFILES_CXX_CSV_ROW := $(OBJFILES_CSV_ROW:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_ROW):
include $(wildcard $(DEPFILES_CXX_CSV_ROW))

#
# csv_column definitions section
#

INC_CSV_COLUMN = $(INC)
CFLAGS_CSV_COLUMN = $(CFLAGS)
LIBDIR_CSV_COLUMN = $(LIBDIR)
LIB_CSV_COLUMN = $(LIB)
LDFLAGS_CSV_COLUMN = $(LDFLAGS)
OBJDIR_CSV_COLUMN = $(OBJDIR)/.csv_column
OUTFILE_CSV_COLUMN = $(OUTDIR)/csv_column
CXX_CSV_COLUMN = $(CXX) $(DEPFLAGS_CXX) $(INC_CSV_COLUMN) $(CFLAGS_CSV_COLUMN) -o $@ -c

$(OBJDIR_CSV_COLUMN)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_CSV_COLUMN)/src/%.cpp.d
	$(CXX_CSV_COLUMN) $<

OBJFILES_CSV_COLUMN = \
	$(OBJDIR_CSV_COLUMN)/src/csv_column.o \
	$(OBJDIR_CSV_COLUMN)/src/csv_usage.o \
	$(OBJDIR_CSV_COLUMN)/src/csvfile.o \
	$(OBJDIR_CSV_COLUMN)/src/ivyhelpers.o \
	$(OBJDIR_CSV_COLUMN)/src/ivytime.o

DEPFILES_CXX_CSV_COLUMN := $(OBJFILES_CSV_COLUMN:%.o=%.cpp.d)
$(DEPFILES_CXX_CSV_COLUMN):
include $(wildcard $(DEPFILES_CXX_CSV_COLUMN))

#
# testregex definitions section
#

INC_TESTREGEX = $(INC)
CFLAGS_TESTREGEX = $(CFLAGS)
LIBDIR_TESTREGEX = $(LIBDIR)
LIB_TESTREGEX = $(LIB)
LDFLAGS_TESTREGEX = $(LDFLAGS)
OBJDIR_TESTREGEX = $(OBJDIR)/.testregex
OUTFILE_TESTREGEX = $(OUTDIR)/testRegex
CXX_TESTREGEX = $(CXX) $(DEPFLAGS_CXX) $(INC_TESTREGEX) $(CFLAGS_TESTREGEX) -o $@ -c

$(OBJDIR_TESTREGEX)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_TESTREGEX)/src/%.cpp.d
	$(CXX_TESTREGEX) $<

OBJFILES_TESTREGEX = \
	$(OBJDIR_TESTREGEX)/src/testRegex.o \
	$(OBJDIR_TESTREGEX)/src/ivyhelpers.o \
	$(OBJDIR_TESTREGEX)/src/ivytime.o

DEPFILES_CXX_TESTREGEX := $(OBJFILES_TESTREGEX:%.o=%.cpp.d)
$(DEPFILES_CXX_TESTREGEX):
include $(wildcard $(DEPFILES_CXX_TESTREGEX))

##
## test_ldevset definition section (Note: Does not build.)
##
#
#INC_TEST_LDEVSET = $(INC)
#CFLAGS_TEST_LDEVSET = $(CFLAGS)
#LIBDIR_TEST_LDEVSET = $(LIBDIR)
#LIB_TEST_LDEVSET = $(LIB)
#LDFLAGS_TEST_LDEVSET = $(LDFLAGS)
#OBJDIR_TEST_LDEVSET = $(OBJDIR)/.test_ldevset
#OUTFILE_TEST_LDEVSET = $(OUTDIR)/ldevset
#CXX_TEST_LDEVSET = $(CXX) $(DEPFLAGS_CXX) $(INC_TEST_LDEVSET) $(CFLAGS_TEST_LDEVSET) -o $@ -c
#
#$(OBJDIR_TEST_LDEVSET)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_TEST_LDEVSET)/src/%.cpp.d
#	$(CXX_TEST_LDEVSET) $<
#
#OBJFILES_TEST_LDEVSET = \
#	$(OBJDIR_TEST_LDEVSET)/src/LDEVset.o \
#	$(OBJDIR_TEST_LDEVSET)/src/test_LDEVset.o \
#	$(OBJDIR_TEST_LDEVSET)/src/ivyhelpers.o \
#	$(OBJDIR_TEST_LDEVSET)/src/ivytime.o
#
#DEPFILES_CXX_TEST_LDEVSET := $(OBJFILES_TEST_LDEVSET:%.o=%.cpp.d)
#$(DEPFILES_CXX_TEST_LDEVSET):
#include $(wildcard $(DEPFILES_CXX_TEST_LDEVSET))

#
# remove_empty_columns definitions section
#

INC_REMOVE_EMPTY_COLUMNS = $(INC)
CFLAGS_REMOVE_EMPTY_COLUMNS = $(CFLAGS)
LIBDIR_REMOVE_EMPTY_COLUMNS = $(LIBDIR)
LIB_REMOVE_EMPTY_COLUMNS = $(LIB)
LDFLAGS_REMOVE_EMPTY_COLUMNS = $(LDFLAGS)
OBJDIR_REMOVE_EMPTY_COLUMNS = $(OBJDIR)/.remove_empty_columns
OUTFILE_REMOVE_EMPTY_COLUMNS = $(OUTDIR)/remove_empty_columns
CXX_REMOVE_EMPTY_COLUMNS = $(CXX) $(DEPFLAGS_CXX) $(INC_REMOVE_EMPTY_COLUMNS) $(CFLAGS_REMOVE_EMPTY_COLUMNS) -o $@ -c

$(OBJDIR_REMOVE_EMPTY_COLUMNS)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_REMOVE_EMPTY_COLUMNS)/src/%.cpp.d
	$(CXX_REMOVE_EMPTY_COLUMNS) $<

OBJFILES_REMOVE_EMPTY_COLUMNS = \
	$(OBJDIR_REMOVE_EMPTY_COLUMNS)/src/remove_empty_columns.o \
	$(OBJDIR_REMOVE_EMPTY_COLUMNS)/src/csvfile.o \
	$(OBJDIR_REMOVE_EMPTY_COLUMNS)/src/ivyhelpers.o \
	$(OBJDIR_REMOVE_EMPTY_COLUMNS)/src/ivytime.o

DEPFILES_CXX_REMOVE_EMPTY_COLUMNS := $(OBJFILES_REMOVE_EMPTY_COLUMNS:%.o=%.cpp.d)
$(DEPFILES_CXX_REMOVE_EMPTY_COLUMNS):
include $(wildcard $(DEPFILES_CXX_REMOVE_EMPTY_COLUMNS))

#
# test_hosts_list definitions section
#

INC_TEST_HOSTS_LIST = $(INC)
CFLAGS_TEST_HOSTS_LIST = $(CFLAGS)
LIBDIR_TEST_HOSTS_LIST = $(LIBDIR)
LIB_TEST_HOSTS_LIST = $(LIB)
LDFLAGS_TEST_HOSTS_LIST = $(LDFLAGS)
OBJDIR_TEST_HOSTS_LIST = $(OBJDIR)/.test_hosts_list
OUTFILE_TEST_HOSTS_LIST = $(OUTDIR)/test_hosts_list
CXX_TEST_HOSTS_LIST = $(CXX) $(DEPFLAGS_CXX) $(INC_TEST_HOSTS_LIST) $(CFLAGS_TEST_HOSTS_LIST) -o $@ -c
CC_TEST_HOSTS_LIST = $(CC) $(DEPFLAGS_CC) $(INC_TEST_HOSTS_LIST) $(CFLAGS_TEST_HOSTS_LIST) -o $@ -c

$(OBJDIR_TEST_HOSTS_LIST)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_TEST_HOSTS_LIST)/src/%.cpp.d
	$(CXX_TEST_HOSTS_LIST) $<

$(OBJDIR_TEST_HOSTS_LIST)/src/hosts/%.o : $(SRCDIR)/hosts/%.cc $(OBJDIR_TEST_HOSTS_LIST)/src/hosts/%.cc.d
	$(CC_TEST_HOSTS_LIST) $<

$(OBJDIR_TEST_HOSTS_LIST)/src/hosts/hosts.scanner.o : $(SRCDIR)/hosts/hosts.scanner.cc
	$(CC_TEST_HOSTS_LIST) $<

$(OBJDIR_TEST_HOSTS_LIST)/src/hosts/hosts.parser.o : $(SRCDIR)/hosts/hosts.parser.cc
	$(CC_TEST_HOSTS_LIST) $<

OBJFILES_TEST_HOSTS_LIST = \
	$(OBJDIR_TEST_HOSTS_LIST)/src/test_hosts_list.o \
	$(OBJDIR_TEST_HOSTS_LIST)/src/hosts_list.o \
	$(OBJDIR_TEST_HOSTS_LIST)/src/hosts/hosts.scanner.o \
	$(OBJDIR_TEST_HOSTS_LIST)/src/hosts/hosts.parser.o

DEPFILES_CXX_TEST_HOSTS_LIST := $(OBJFILES_TEST_HOSTS_LIST:%.o=%.cpp.d)
$(DEPFILES_CXX_TEST_HOSTS_LIST):
include $(wildcard $(DEPFILES_CXX_TEST_HOSTS_LIST))

#
# test_negative_ivytimes definition section
#

INC_TEST_NEGATIVE_IVYTIMES = $(INC)
CFLAGS_TEST_NEGATIVE_IVYTIMES = $(CFLAGS) -O2
LIBDIR_TEST_NEGATIVE_IVYTIMES = $(LIBDIR)
LIB_TEST_NEGATIVE_IVYTIMES = $(LIB)
LDFLAGS_TEST_NEGATIVE_IVYTIMES = $(LDFLAGS) -s
OBJDIR_TEST_NEGATIVE_IVYTIMES = $(OBJDIR)/.test_negative_ivytimes
OUTFILE_TEST_NEGATIVE_IVYTIMES = $(OUTDIR)/test_negative_ivytimes/ivy
CXX_TEST_NEGATIVE_IVYTIMES = $(CXX) $(DEPFLAGS_CXX) $(INC_TEST_NEGATIVE_IVYTIMES) $(CFLAGS_TEST_NEGATIVE_IVYTIMES) -o $@ -c

$(OBJDIR_TEST_NEGATIVE_IVYTIMES)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_TEST_NEGATIVE_IVYTIMES)/src/%.cpp.d
	$(CXX_TEST_NEGATIVE_IVYTIMES) $<

OBJFILES_TEST_NEGATIVE_IVYTIMES = \
	$(OBJDIR_TEST_NEGATIVE_IVYTIMES)/src/test_negative_ivytimes.o \
	$(OBJDIR_TEST_NEGATIVE_IVYTIMES)/src/ivytime.o

DEPFILES_CXX_TEST_NEGATIVE_IVYTIMES := $(OBJFILES_TEST_NEGATIVE_IVYTIMES:%.o=%.cpp.d)
$(DEPFILES_CXX_TEST_NEGATIVE_IVYTIMES):
include $(wildcard $(DEPFILES_CXX_TEST_NEGATIVE_IVYTIMES))

#
# ivycore definition section
#

INC_IVYCORE = $(INC)
CFLAGS_IVYCORE = $(CFLAGS)
LIBDIR_IVYCORE = $(LIBDIR)
LIB_IVYCORE = $(LIB)
LDFLAGS_IVYCORE = $(LDFLAGS)
OBJDIR_IVYCORE = $(OBJDIR)/.ivycore
OUTFILE_IVYCORE = $(OUTDIR)/ivycore
CXX_IVYCORE = $(CXX) $(DEPFLAGS_CXX) $(INC_IVYCORE) $(CFLAGS_IVYCORE) -o $@ -c

$(OBJDIR_IVYCORE)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_IVYCORE)/src/%.cpp.d
	$(CXX_IVYCORE) $<

OBJFILES_IVYCORE = \
	$(OBJDIR_IVYCORE)/src/ivycore.o \
	$(OBJDIR_IVYCORE)/src/ivyhelpers.o \
	$(OBJDIR_IVYCORE)/src/ivytime.o

DEPFILES_CXX_IVYCORE := $(OBJFILES_IVYCORE:%.o=%.cpp.d)
$(DEPFILES_CXX_IVYCORE):
include $(wildcard $(DEPFILES_CXX_IVYCORE))

#
# dedupeconstantratiotablegenerator definition section
#

INC_DEDUPECONSTANTRATIO = $(INC)
CFLAGS_DEDUPECONSTANTRATIO = $(CFLAGS)
LIBDIR_DEDUPECONSTANTRATIO = $(LIBDIR)
LIB_DEDUPECONSTANTRATIO = $(LIB)
LDFLAGS_DEDUPECONSTANTRATIO = $(LDFLAGS)
OBJDIR_DEDUPECONSTANTRATIO = $(OBJDIR)/.dedupeconstantratiotablegenerator
OUTFILE_DEDUPECONSTANTRATIO = $(OUTDIR)/DedupeConstantRatioTableGenerator
CXX_DEDUPECONSTANTRATIO = $(CXX) $(DEPFLAGS_CXX) $(INC_DEDUPECONSTANTRATIO) $(CFLAGS_DEDUPECONSTANTRATIO) -o $@ -c

$(OBJDIR_DEDUPECONSTANTRATIO)/src/%.o : $(SRCDIR)/%.cpp $(OBJDIR_DEDUPECONSTANTRATIO)/src/%.cpp.d
	$(CXX_DEDUPECONSTANTRATIO) $<

OBJFILES_DEDUPECONSTANTRATIO = \
	$(OBJDIR_DEDUPECONSTANTRATIO)/src/DedupeConstantRatioTable.o

DEPFILES_CXX_DEDUPECONSTANTRATIO := $(OBJFILES_DEDUPECONSTANTRATIO:%.o=%.cpp.d)
$(DEPFILES_CXX_DEDUPECONSTANTRATIO):
include $(wildcard $(DEPFILES_CXX_DEDUPECONSTANTRATIO))

#=====

#
# build section
#

csv_utilities: \
	csv_rows \
	csv_header_columns \
	csv_columns_in_row \
	csv_column_header \
	csv_raw_cell_value \
	csv_cell_value \
	csv_lookup_column \
	csv_row \
	csv_column \
	remove_empty_columns

base: \
	$(SRCDIR)/select/select.scanner.cc \
	$(SRCDIR)/select/select.parser.cc \
	parser/lexyacc/ivy.scanner.cc \
	parser/lexyacc/ivy.parser.cc \
	$(SRCDIR)/hosts/hosts.scanner.cc \
	$(SRCDIR)/hosts/hosts.parser.cc

clean_base:
	rm -f parser/lexyacc/ivy.scanner.cc
	rm -f parser/lexyacc/ivy.parser.cc
	rm -f parser/lexyacc/ivy.parser.hh
	rm -f parser/lexyacc/ivy.parser.output
	rm -f parser/lexyacc/location.hh
	rm -f parser/lexyacc/position.hh
	rm -f parser/lexyacc/stack.hh
	rm -f src/hosts/hosts.parser.cc
	rm -f src/hosts/hosts.parser.hh
	rm -f src/hosts/hosts.parser.output
	rm -f src/hosts/hosts.scanner.cc
	rm -f src/hosts/location.hh
	rm -f src/hosts/position.hh
	rm -f src/hosts/stack.hh
	rm -f src/select/select.scanner.cc
	rm -f src/select/select.parser.cc
	rm -f src/select/select.parser.hh
	rm -f src/select/select.parser.output
	rm -f src/select/location.hh
	rm -f src/select/position.hh
	rm -f src/select/stack.hh

all: \
	ivymaster \
	ivydriver \
	clear_hung_ivy_threads \
	makedict \
	csv_rows \
	csv_header_columns \
	csv_columns_in_row \
	csv_column_header \
	csv_raw_cell_value \
	csv_cell_value \
	csv_lookup_column \
	csv_row \
	csv_column \
	testregex \
	test_hosts_list \
	remove_empty_columns \
	test_negative_ivytimes \
	ivycore \
	dedupeconstantratiotablegenerator

clean_main: \
	clean_ivymaster \
	clean_ivydriver \
	remove_empty_columns

clean_csv_utilities: \
	clean_csv_rows \
	clean_csv_header_columns \
	clean_csv_columns_in_row \
	clean_csv_column_header \
	clean_csv_raw_cell_value \
	clean_csv_cell_value \
	clean_csv_lookup_column \
	clean_csv_row \
	clean_csv_column \
	clean_remove_empty_columns

clean: \
	clean_ivymaster \
	clean_ivydriver \
	clean_clear_hung_ivy_threads \
	clean_makedict \
	clean_csv_rows \
	clean_csv_header_columns \
	clean_csv_columns_in_row \
	clean_csv_column_header \
	clean_csv_raw_cell_value \
	clean_csv_cell_value \
	clean_csv_lookup_column \
	clean_csv_row \
	clean_csv_column \
	clean_testregex \
	clean_remove_empty_columns \
	clean_test_hosts_list \
	clean_test_negative_ivytimes \
	clean_ivycore \
	clean_dedupeconstantratiotablegenerator

distclean: \
	clean
	rm -rf $(OUTDIR)

before_ivymaster:
	touch include/ivybuilddate.h
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_IVYMASTER) || mkdir -p $(OBJDIR_IVYMASTER)
	test -d $(OBJDIR_IVYMASTER)/src || mkdir -p $(OBJDIR_IVYMASTER)/src
	test -d $(OBJDIR_IVYMASTER)/__/LUN_discovery/src || mkdir -p $(OBJDIR_IVYMASTER)/__/LUN_discovery/src
	test -d $(OBJDIR_IVYMASTER)/parser/src || mkdir -p $(OBJDIR_IVYMASTER)/parser/src
	test -d $(OBJDIR_IVYMASTER)/parser/lexyacc || mkdir -p $(OBJDIR_IVYMASTER)/parser/lexyacc
	test -d $(OBJDIR_IVYMASTER)/src/select || mkdir -p $(OBJDIR_IVYMASTER)/src/select
	test -d $(OBJDIR_IVYMASTER)/src/hosts || mkdir -p $(OBJDIR_IVYMASTER)/src/hosts

after_ivymaster:

ivymaster: base before_ivymaster out_ivymaster after_ivymaster

out_ivymaster: before_ivymaster $(OBJFILES_IVYMASTER)
	$(LD) $(LIBDIR_IVYMASTER) -o $(OUTFILE_IVYMASTER) $(OBJFILES_IVYMASTER) $(LDFLAGS_IVYMASTER) $(LIB_IVYMASTER)

clean_ivymaster:
	rm -f $(OUTFILE_IVYMASTER)
	rm -f $(OBJFILES_IVYMASTER)
	rm -rf $(OBJDIR_IVYMASTER)

before_ivydriver:
	touch include/ivybuilddate.h
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_IVYDRIVER) || mkdir -p $(OBJDIR_IVYDRIVER)
	test -d $(OBJDIR_IVYDRIVER)/src || mkdir -p $(OBJDIR_IVYDRIVER)/src
	test -d $(OBJDIR_IVYDRIVER)/__/LUN_discovery/src || mkdir -p $(OBJDIR_IVYDRIVER)/__/LUN_discovery/src

after_ivydriver:

ivydriver: before_ivydriver out_ivydriver after_ivydriver

out_ivydriver: before_ivydriver $(OBJFILES_IVYDRIVER)
	$(LD) $(LIBDIR_IVYDRIVER) -o $(OUTFILE_IVYDRIVER) $(OBJFILES_IVYDRIVER)  $(LDFLAGS_IVYDRIVER) $(LIB_IVYDRIVER)

clean_ivydriver:
	rm -f $(OUTFILE_IVYDRIVER)
	rm -f $(OBJFILES_IVYDRIVER)
	rm -rf $(OBJDIR_IVYDRIVER)

before_clear_hung_ivy_threads:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CLEAR_HUNG_IVY_THREADS) || mkdir -p $(OBJDIR_CLEAR_HUNG_IVY_THREADS)
	test -d $(OBJDIR_CLEAR_HUNG_IVY_THREADS)/src || mkdir -p $(OBJDIR_CLEAR_HUNG_IVY_THREADS)/src

after_clear_hung_ivy_threads:

clear_hung_ivy_threads: before_clear_hung_ivy_threads out_clear_hung_ivy_threads after_clear_hung_ivy_threads

out_clear_hung_ivy_threads: before_clear_hung_ivy_threads $(OBJFILES_CLEAR_HUNG_IVY_THREADS)
	$(LD) $(LIBDIR_CLEAR_HUNG_IVY_THREADS) -o $(OUTFILE_CLEAR_HUNG_IVY_THREADS) $(OBJFILES_CLEAR_HUNG_IVY_THREADS)  $(LDFLAGS_CLEAR_HUNG_IVY_THREADS) $(LIB_CLEAR_HUNG_IVY_THREADS)

clean_clear_hung_ivy_threads:
	rm -f $(OUTFILE_CLEAR_HUNG_IVY_THREADS)
	rm -f $(OBJFILES_CLEAR_HUNG_IVY_THREADS)
	rm -rf $(OBJDIR_CLEAR_HUNG_IVY_THREADS)

before_makedict:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_MAKEDICT) || mkdir -p $(OBJDIR_MAKEDICT)
	test -d $(OBJDIR_MAKEDICT)/src || mkdir -p $(OBJDIR_MAKEDICT)/src

after_makedict:

makedict: before_makedict out_makedict after_makedict

out_makedict: before_makedict $(OBJFILES_MAKEDICT)
	$(LD) $(LIBDIR_MAKEDICT) -o $(OUTFILE_MAKEDICT) $(OBJFILES_MAKEDICT)  $(LDFLAGS_MAKEDICT) $(LIB_MAKEDICT)

clean_makedict:
	rm -f $(OUTFILE_MAKEDICT)
	rm -f $(OBJFILES_MAKEDICT)
	rm -rf $(OBJDIR_MAKEDICT)

before_csv_rows:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_ROWS) || mkdir -p $(OBJDIR_CSV_ROWS)
	test -d $(OBJDIR_CSV_ROWS)/src || mkdir -p $(OBJDIR_CSV_ROWS)/src

after_csv_rows:

csv_rows: before_csv_rows out_csv_rows after_csv_rows

out_csv_rows: before_csv_rows $(OBJFILES_CSV_ROWS)
	$(LD) $(LIBDIR_CSV_ROWS) -o $(OUTFILE_CSV_ROWS) $(OBJFILES_CSV_ROWS)  $(LDFLAGS_CSV_ROWS) $(LIB_CSV_ROWS)

clean_csv_rows:
	rm -f $(OUTFILE_CSV_ROWS)
	rm -f $(OBJFILES_CSV_ROWS)
	rm -rf $(OBJDIR_CSV_ROWS)

before_csv_header_columns:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_HEADER_COLUMNS) || mkdir -p $(OBJDIR_CSV_HEADER_COLUMNS)
	test -d $(OBJDIR_CSV_HEADER_COLUMNS)/src || mkdir -p $(OBJDIR_CSV_HEADER_COLUMNS)/src

after_csv_header_columns:

csv_header_columns: before_csv_header_columns out_csv_header_columns after_csv_header_columns

out_csv_header_columns: before_csv_header_columns $(OBJFILES_CSV_HEADER_COLUMNS)
	$(LD) $(LIBDIR_CSV_HEADER_COLUMNS) -o $(OUTFILE_CSV_HEADER_COLUMNS) $(OBJFILES_CSV_HEADER_COLUMNS)  $(LDFLAGS_CSV_HEADER_COLUMNS) $(LIB_CSV_HEADER_COLUMNS)

clean_csv_header_columns:
	rm -f $(OUTFILE_CSV_HEADER_COLUMNS)
	rm -f $(OBJFILES_CSV_HEADER_COLUMNS)
	rm -rf $(OBJDIR_CSV_HEADER_COLUMNS)

before_csv_columns_in_row:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_COLUMNS_IN_ROW) || mkdir -p $(OBJDIR_CSV_COLUMNS_IN_ROW)
	test -d $(OBJDIR_CSV_COLUMNS_IN_ROW)/src || mkdir -p $(OBJDIR_CSV_COLUMNS_IN_ROW)/src

after_csv_columns_in_row:

csv_columns_in_row: before_csv_columns_in_row out_csv_columns_in_row after_csv_columns_in_row

out_csv_columns_in_row: before_csv_columns_in_row $(OBJFILES_CSV_COLUMNS_IN_ROW)
	$(LD) $(LIBDIR_CSV_COLUMNS_IN_ROW) -o $(OUTFILE_CSV_COLUMNS_IN_ROW) $(OBJFILES_CSV_COLUMNS_IN_ROW)  $(LDFLAGS_CSV_COLUMNS_IN_ROW) $(LIB_CSV_COLUMNS_IN_ROW)

clean_csv_columns_in_row:
	rm -f $(OUTFILE_CSV_COLUMNS_IN_ROW)
	rm -f $(OBJFILES_CSV_COLUMNS_IN_ROW)
	rm -rf $(OBJDIR_CSV_COLUMNS_IN_ROW)

before_csv_column_header:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_COLUMN_HEADER) || mkdir -p $(OBJDIR_CSV_COLUMN_HEADER)
	test -d $(OBJDIR_CSV_COLUMN_HEADER)/src || mkdir -p $(OBJDIR_CSV_COLUMN_HEADER)/src

after_csv_column_header:

csv_column_header: before_csv_column_header out_csv_column_header after_csv_column_header

out_csv_column_header: before_csv_column_header $(OBJFILES_CSV_COLUMN_HEADER)
	$(LD) $(LIBDIR_CSV_COLUMN_HEADER) -o $(OUTFILE_CSV_COLUMN_HEADER) $(OBJFILES_CSV_COLUMN_HEADER)  $(LDFLAGS_CSV_COLUMN_HEADER) $(LIB_CSV_COLUMN_HEADER)

clean_csv_column_header:
	rm -f $(OUTFILE_CSV_COLUMN_HEADER)
	rm -f $(OBJFILES_CSV_COLUMN_HEADER)
	rm -rf $(OBJDIR_CSV_COLUMN_HEADER)

before_csv_raw_cell_value:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_RAW_CELL_VALUE) || mkdir -p $(OBJDIR_CSV_RAW_CELL_VALUE)
	test -d $(OBJDIR_CSV_RAW_CELL_VALUE)/src || mkdir -p $(OBJDIR_CSV_RAW_CELL_VALUE)/src

after_csv_raw_cell_value:

csv_raw_cell_value: before_csv_raw_cell_value out_csv_raw_cell_value after_csv_raw_cell_value

out_csv_raw_cell_value: before_csv_raw_cell_value $(OBJFILES_CSV_RAW_CELL_VALUE)
	$(LD) $(LIBDIR_CSV_RAW_CELL_VALUE) -o $(OUTFILE_CSV_RAW_CELL_VALUE) $(OBJFILES_CSV_RAW_CELL_VALUE)  $(LDFLAGS_CSV_RAW_CELL_VALUE) $(LIB_CSV_RAW_CELL_VALUE)

clean_csv_raw_cell_value:
	rm -f $(OUTFILE_CSV_RAW_CELL_VALUE)
	rm -f $(OBJFILES_CSV_RAW_CELL_VALUE)
	rm -rf $(OBJDIR_CSV_RAW_CELL_VALUE)

before_csv_cell_value:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_CELL_VALUE) || mkdir -p $(OBJDIR_CSV_CELL_VALUE)
	test -d $(OBJDIR_CSV_CELL_VALUE)/src || mkdir -p $(OBJDIR_CSV_CELL_VALUE)/src

after_csv_cell_value:

csv_cell_value: before_csv_cell_value out_csv_cell_value after_csv_cell_value

out_csv_cell_value: before_csv_cell_value $(OBJFILES_CSV_CELL_VALUE)
	$(LD) $(LIBDIR_CSV_CELL_VALUE) -o $(OUTFILE_CSV_CELL_VALUE) $(OBJFILES_CSV_CELL_VALUE)  $(LDFLAGS_CSV_CELL_VALUE) $(LIB_CSV_CELL_VALUE)

clean_csv_cell_value:
	rm -f $(OUTFILE_CSV_CELL_VALUE)
	rm -f $(OBJFILES_CSV_CELL_VALUE)
	rm -rf $(OBJDIR_CSV_CELL_VALUE)

before_csv_lookup_column:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_LOOKUP_COLUMN) || mkdir -p $(OBJDIR_CSV_LOOKUP_COLUMN)
	test -d $(OBJDIR_CSV_LOOKUP_COLUMN)/src || mkdir -p $(OBJDIR_CSV_LOOKUP_COLUMN)/src

after_csv_lookup_column:

csv_lookup_column: before_csv_lookup_column out_csv_lookup_column after_csv_lookup_column

out_csv_lookup_column: before_csv_lookup_column $(OBJFILES_CSV_LOOKUP_COLUMN)
	$(LD) $(LIBDIR_CSV_LOOKUP_COLUMN) -o $(OUTFILE_CSV_LOOKUP_COLUMN) $(OBJFILES_CSV_LOOKUP_COLUMN)  $(LDFLAGS_CSV_LOOKUP_COLUMN) $(LIB_CSV_LOOKUP_COLUMN)

clean_csv_lookup_column:
	rm -f $(OUTFILE_CSV_LOOKUP_COLUMN)
	rm -f $(OBJFILES_CSV_LOOKUP_COLUMN)
	rm -rf $(OBJDIR_CSV_LOOKUP_COLUMN)

before_csv_row:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_ROW) || mkdir -p $(OBJDIR_CSV_ROW)
	test -d $(OBJDIR_CSV_ROW)/src || mkdir -p $(OBJDIR_CSV_ROW)/src

after_csv_row:

csv_row: before_csv_row out_csv_row after_csv_row

out_csv_row: before_csv_row $(OBJFILES_CSV_ROW)
	$(LD) $(LIBDIR_CSV_ROW) -o $(OUTFILE_CSV_ROW) $(OBJFILES_CSV_ROW)  $(LDFLAGS_CSV_ROW) $(LIB_CSV_ROW)

clean_csv_row:
	rm -f $(OUTFILE_CSV_ROW)
	rm -f $(OBJFILES_CSV_ROW)
	rm -rf $(OBJDIR_CSV_ROW)

before_csv_column:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_CSV_COLUMN) || mkdir -p $(OBJDIR_CSV_COLUMN)
	test -d $(OBJDIR_CSV_COLUMN)/src || mkdir -p $(OBJDIR_CSV_COLUMN)/src

after_csv_column:

csv_column: before_csv_column out_csv_column after_csv_column

out_csv_column: before_csv_column $(OBJFILES_CSV_COLUMN)
	$(LD) $(LIBDIR_CSV_COLUMN) -o $(OUTFILE_CSV_COLUMN) $(OBJFILES_CSV_COLUMN)  $(LDFLAGS_CSV_COLUMN) $(LIB_CSV_COLUMN)

clean_csv_column:
	rm -f $(OUTFILE_CSV_COLUMN)
	rm -f $(OBJFILES_CSV_COLUMN)
	rm -rf $(OBJDIR_CSV_COLUMN)

before_testregex:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_TESTREGEX) || mkdir -p $(OBJDIR_TESTREGEX)
	test -d $(OBJDIR_TESTREGEX)/src || mkdir -p $(OBJDIR_TESTREGEX)/src

after_testregex:

testregex: before_testregex out_testregex after_testregex

out_testregex: before_testregex $(OBJFILES_TESTREGEX)
	$(LD) $(LIBDIR_TESTREGEX) -o $(OUTFILE_TESTREGEX) $(OBJFILES_TESTREGEX)  $(LDFLAGS_TESTREGEX) $(LIB_TESTREGEX)

clean_testregex:
	rm -f $(OUTFILE_TESTREGEX)
	rm -f $(OBJFILES_TESTREGEX)
	rm -rf $(OBJDIR_TESTREGEX)

#before_test_ldevset:
#	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
#	test -d $(OBJDIR_TEST_LDEVSET) || mkdir -p $(OBJDIR_TEST_LDEVSET)
#	test -d $(OBJDIR_TEST_LDEVSET)/src || mkdir -p $(OBJDIR_TEST_LDEVSET)/src
#
#after_test_ldevset:
#
#test_ldevset: before_test_ldevset out_test_ldevset after_test_ldevset
#
#out_test_ldevset: before_test_ldevset $(OBJFILES_TEST_LDEVSET)
#	$(LD) $(LIBDIR_TEST_LDEVSET) -o $(OUTFILE_TEST_LDEVSET) $(OBJFILES_TEST_LDEVSET)  $(LDFLAGS_TEST_LDEVSET) $(LIB_TEST_LDEVSET)
#
#clean_test_ldevset:
#	rm -f $(OUTFILE_TEST_LDEVSET)
#	rm -f $(OBJFILES_TEST_LDEVSET)
#	rm -rf $(OBJDIR_TEST_LDEVSET)

before_remove_empty_columns:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_REMOVE_EMPTY_COLUMNS) || mkdir -p $(OBJDIR_REMOVE_EMPTY_COLUMNS)
	test -d $(OBJDIR_REMOVE_EMPTY_COLUMNS)/src || mkdir -p $(OBJDIR_REMOVE_EMPTY_COLUMNS)/src

after_remove_empty_columns:

remove_empty_columns: before_remove_empty_columns out_remove_empty_columns after_remove_empty_columns

out_remove_empty_columns: before_remove_empty_columns $(OBJFILES_REMOVE_EMPTY_COLUMNS)
	$(LD) $(LIBDIR_REMOVE_EMPTY_COLUMNS) -o $(OUTFILE_REMOVE_EMPTY_COLUMNS) $(OBJFILES_REMOVE_EMPTY_COLUMNS)  $(LDFLAGS_REMOVE_EMPTY_COLUMNS) $(LIB_REMOVE_EMPTY_COLUMNS)

clean_remove_empty_columns:
	rm -f $(OUTFILE_REMOVE_EMPTY_COLUMNS)
	rm -f $(OBJFILES_REMOVE_EMPTY_COLUMNS)
	rm -rf $(OBJDIR_REMOVE_EMPTY_COLUMNS)

before_test_hosts_list:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_TEST_HOSTS_LIST) || mkdir -p $(OBJDIR_TEST_HOSTS_LIST)
	test -d $(OBJDIR_TEST_HOSTS_LIST)/src || mkdir -p $(OBJDIR_TEST_HOSTS_LIST)/src
	test -d $(OBJDIR_TEST_HOSTS_LIST)/src/hosts || mkdir -p $(OBJDIR_TEST_HOSTS_LIST)/src/hosts

after_test_hosts_list:

test_hosts_list: base before_test_hosts_list out_test_hosts_list after_test_hosts_list

out_test_hosts_list: before_test_hosts_list $(OBJFILES_TEST_HOSTS_LIST)
	$(LD) $(LIBDIR_TEST_HOSTS_LIST) -o $(OUTFILE_TEST_HOSTS_LIST) $(OBJFILES_TEST_HOSTS_LIST)  $(LDFLAGS_TEST_HOSTS_LIST) $(LIB_TEST_HOSTS_LIST)

clean_test_hosts_list:
	rm -f $(OUTFILE_TEST_HOSTS_LIST)
	rm -f $(OBJFILES_TEST_HOSTS_LIST)
	rm -rf $(OBJDIR_TEST_HOSTS_LIST)

before_test_negative_ivytimes:
	test -d $(OUTDIR)/test_negative_ivytimes || mkdir -p $(OUTDIR)/test_negative_ivytimes
	test -d $(OBJDIR_TEST_NEGATIVE_IVYTIMES) || mkdir -p $(OBJDIR_TEST_NEGATIVE_IVYTIMES)
	test -d $(OBJDIR_TEST_NEGATIVE_IVYTIMES)/src || mkdir -p $(OBJDIR_TEST_NEGATIVE_IVYTIMES)/src

after_test_negative_ivytimes:

test_negative_ivytimes: before_test_negative_ivytimes out_test_negative_ivytimes after_test_negative_ivytimes

out_test_negative_ivytimes: before_test_negative_ivytimes $(OBJFILES_TEST_NEGATIVE_IVYTIMES)
	$(LD) $(LIBDIR_TEST_NEGATIVE_IVYTIMES) -o $(OUTFILE_TEST_NEGATIVE_IVYTIMES) $(OBJFILES_TEST_NEGATIVE_IVYTIMES)  $(LDFLAGS_TEST_NEGATIVE_IVYTIMES) $(LIB_TEST_NEGATIVE_IVYTIMES)

clean_test_negative_ivytimes:
	rm -f $(OUTFILE_TEST_NEGATIVE_IVYTIMES)
	rm -f $(OBJFILES_TEST_NEGATIVE_IVYTIMES)
	rm -rf $(OBJDIR_TEST_NEGATIVE_IVYTIMES)

before_ivycore:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_IVYCORE) || mkdir -p $(OBJDIR_IVYCORE)
	test -d $(OBJDIR_IVYCORE)/src || mkdir -p $(OBJDIR_IVYCORE)/src

after_ivycore:

ivycore: before_ivycore out_ivycore after_ivycore

out_ivycore: before_ivycore $(OBJFILES_IVYCORE)
	$(LD) $(LIBDIR_IVYCORE) -o $(OUTFILE_IVYCORE) $(OBJFILES_IVYCORE)  $(LDFLAGS_IVYCORE) $(LIB_IVYCORE)

clean_ivycore:
	rm -f $(OUTFILE_IVYCORE)
	rm -f $(OBJFILES_IVYCORE)
	rm -rf $(OBJDIR_IVYCORE)

before_dedupeconstantratiotablegenerator:
	test -d $(OUTDIR) || mkdir -p $(OUTDIR)
	test -d $(OBJDIR_DEDUPECONSTANTRATIO) || mkdir -p $(OBJDIR_DEDUPECONSTANTRATIO)
	test -d $(OBJDIR_DEDUPECONSTANTRATIO)/src || mkdir -p $(OBJDIR_DEDUPECONSTANTRATIO)/src

after_dedupeconstantratiotablegenerator:

dedupeconstantratiotablegenerator: before_dedupeconstantratiotablegenerator out_dedupeconstantratiotablegenerator after_dedupeconstantratiotablegenerator

out_dedupeconstantratiotablegenerator: before_dedupeconstantratiotablegenerator $(OBJFILES_DEDUPECONSTANTRATIO)
	$(LD) $(LIBDIR_DEDUPECONSTANTRATIO) -o $(OUTFILE_DEDUPECONSTANTRATIO) $(OBJFILES_DEDUPECONSTANTRATIO)  $(LDFLAGS_DEDUPECONSTANTRATIO) $(LIB_DEDUPECONSTANTRATIO)

clean_dedupeconstantratiotablegenerator:
	rm -f $(OUTFILE_DEDUPECONSTANTRATIO)
	rm -f $(OBJFILES_DEDUPECONSTANTRATIO)
	rm -rf $(OBJDIR_DEDUPECONSTANTRATIO)

virtual_all: \
	ivymaster \
	ivydriver \
	clear_hung_ivy_threads

#
# Note: *_test_ldevset have been removed from this list as test_ldevset does not build.
#
.PHONY: \
	before_ivymaster \
	after_ivymaster \
	clean_ivymaster \
	before_ivydriver \
	after_ivydriver \
	clean_ivydriver \
	before_clear_hung_ivy_threads \
	after_clear_hung_ivy_threads \
	clean_clear_hung_ivy_threads \
	before_makedict \
	after_makedict \
	clean_makedict \
	before_csv_rows \
	after_csv_rows \
	clean_csv_rows \
	before_csv_header_columns \
	after_csv_header_columns \
	clean_csv_header_columns \
	before_csv_columns_in_row \
	after_csv_columns_in_row \
	clean_csv_columns_in_row \
	before_csv_column_header \
	after_csv_column_header \
	clean_csv_column_header \
	before_csv_raw_cell_value \
	after_csv_raw_cell_value \
	clean_csv_raw_cell_value \
	before_csv_cell_value \
	after_csv_cell_value \
	clean_csv_cell_value \
	before_csv_lookup_column \
	after_csv_lookup_column \
	clean_csv_lookup_column \
	before_csv_row \
	after_csv_row \
	clean_csv_row \
	before_csv_column \
	after_csv_column \
	clean_csv_column \
	before_testregex \
	after_testregex \
	clean_testregex  \
	before_remove_empty_columns \
	after_remove_empty_columns \
	clean_remove_empty_columns \
	before_test_hosts_list \
	after_test_hosts_list \
	clean_test_hosts_list \
	before_test_negative_ivytimes \
	after_test_negative_ivytimes \
	clean_test_negative_ivytimes \
	before_ivycore \
	after_ivycore \
	clean_ivycore \
	before_dedupeconstantratiotablegenerator \
	after_dedupeconstantratiotablegenerator \
	clean_dedupeconstantratiotablegenerator
